In [1]:
import numpy as np
from numpy import linalg as la

n = int(input('n = '))

n = 5


In [2]:
#Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).
rev_arr = np.flip(np.arange(n))
print(rev_arr)

[4 3 2 1 0]


In [3]:
#Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

diag_arr = np.diag(rev_arr)
print(diag_arr)

np.trace(diag_arr)

[[4 0 0 0 0]
 [0 3 0 0 0]
 [0 0 2 0 0]
 [0 0 0 1 0]
 [0 0 0 0 0]]


10

In [4]:
'''Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3'''


a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )
b = np.array( [4, 12, -3] )
la.solve(a, b)

#np.allclose(np.dot(a, la.solve(a, b)), b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [5]:
#Найти самого похожего пользователя из массива user_stats
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ]
)
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

cosines = []
norm_nus = la.norm(next_user_stats)
for u_id, u_vector in enumerate(users_stats):
    user_vector = [u_vector]
    norm_vector = la.norm(user_vector)
    cosines.append(((np.dot(user_vector, next_user_stats) / (norm_vector * norm_nus)), u_id))
print(max(cosines))

(array([0.9486833]), 7)
